name: pets
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

#  state management
  get: ^4.6.1

#  image
  cached_network_image: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
flutter:
  uses-material-design: true

  fonts:
    - family: Thin
      fonts:
        - asset: assets/fonts/Poppins-Thin.ttf
    - family: Light
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
    - family: Regular
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
    - family: Medium
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
    - family: Thick
      fonts:
        - asset: assets/fonts/Poppins-Black.ttf
    - family: Bold
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
    - family: EBold
      fonts:
        - asset: assets/fonts/Poppins-ExtraBold.ttf
